mkdir checkpoints
cd checkpoints
# vox.pth.tar
gdown 1-CKOjv_y_TzNe-dwQsjjeVxJUuyBAb5X
# ted.pth.tar
gdown 1Oy2X7DTXp8OdbMesQ6bLzJ_sR8X86DtB
# taichi.pth.tar
gdown 1gZiUyhGZV0AYZ1G9aBtxYMxSdcBW9kc4
# mgif.pth.tar
gdown 1zwhsHvRt8-ymhkLXC8iglp-h7A8x7XJY